T 32 read me frontend
TeamUp3Batch/yummydash-frontend pull request #17
Opened 2023-10-13 23:22 UTC by anithaamarnath

Read me FIle for the front end

2023-10-14 06:22 UTC, KatePolyakov approved these changes

2023-10-14 09:32 UTC, kavithashanmugan requested changes
Food App inspired from the popular app- Skip The Dishes
The Yummy Dash web App is an ambitious project designed to
from their comfort of their homes
create .env file in your root dir and check the .envSample file for backend url variable

2023-10-15 04:48 UTC, TeamUp3Batch approved these changes

2023-10-18 18:26 UTC, kavithashanmugan approved these changes

2023-10-18 18:27 UTC, merged