Tu 36 UI display menu
TeamUp3Batch/yummydash-frontend pull request #19
Opened 2023-10-20 00:23 UTC by KatePolyakov

2023-10-20 00:33 UTC, anithaamarnath requested changes

2023-10-20 00:33 UTC, anithaamarnath commented on src/api/ApiLinks.jsx
> +export const CuisinesURL = `${process.env.REACT_APP_BACKEND_URL}/api/cuisines/getAllCuisines`;
@KatePolyakov can u merger main and change the folder accordingly 
please thank

2023-10-20 00:33 UTC, anithaamarnath commented on src/components/Menu/Menu.jsx
> +  useEffect(() => {
this should move to services folder

2023-10-20 00:42 UTC, anithaamarnath requested changes

2023-10-20 00:42 UTC, anithaamarnath commented on src/api/ApiLinks.jsx
> +export const CuisinesURL = `${process.env.REACT_APP_BACKEND_URL}/api/cuisines/getAllCuisines`;
also Delete this ApiLinks file

2023-10-20 00:42 UTC, anithaamarnath commented on src/components/Menu/Menu.jsx
> +          {restaurants._id === '651e32d67a5bb9de20aaf7ec' ? (
No harded  code the ID  and follow the main branch folder structure eg: Login Componement

2023-10-31 06:19 UTC, KatePolyakov commented on src/components/Menu/Menu.jsx
> +  useEffect(() => {
did it

2023-11-04 08:17 UTC, KatePolyakov commented
TU-36-UI-On click restuarant-display menu

2023-11-04 15:22 UTC, anithaamarnath approved these changes

2023-11-04 19:48 UTC, anithaamarnath approved these changes

2023-11-04 19:49 UTC, TeamUp3Batch approved these changes

2023-11-04 20:15 UTC, anithaamarnath approved these changes

2023-11-04 20:15 UTC, merged