Tu 44 api fixes
TeamUp3Batch/yummydash-frontend pull request #20
Opened 2023-10-20 20:57 UTC by kavithashanmugan

2023-10-20 21:20 UTC, anithaamarnath requested changes

2023-10-20 21:20 UTC, anithaamarnath commented on src/components/RestaurantList/hooks/useFetchRestaurants.jsx
> +        console.log("selectedcuisne", selectedCuisine === null);
remove the console.log please

2023-10-20 21:20 UTC, anithaamarnath commented on src/services/restaurantService.js
> +    const result = await axios.get(url);
Nice , used GET has DJ Suggested

2023-10-21 05:21 UTC, TeamUp3Batch approved these changes

2023-10-21 05:22 UTC, anithaamarnath approved these changes

2023-10-21 05:23 UTC, merged