TU - 11 -display in profile page -UI
TeamUp3Batch/yummydash-frontend pull request #21
Opened 2023-10-26 19:34 UTC by TeamUp3Batch

TU - 11 -display in profile page changes

2023-10-26 19:48 UTC, anithaamarnath requested changes
For me, it looks great, once file name consistency ViewAccount folder(Profile) naming conversion or vice versa

2023-10-26 19:48 UTC, anithaamarnath commented on src/pages/Header/Header.jsx
>        console.log(error);
Remove the console.log , thanks

2023-10-26 19:48 UTC, anithaamarnath commented on yammydash.code-workspace
> +	"folders": [
I have no idea about this file

2023-10-26 19:48 UTC, anithaamarnath commented on how
> +[33mcommit 326407dc13477995ad8d8686c1e625707bcbd266[m[33m ([m[1;36mHEAD -> [m[1;32mnaser-frontend[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m, [m[1;32mmain[m[33m)
Remove this file, would be great, Thank u

2023-10-27 00:46 UTC, anithaamarnath approved these changes

2023-10-27 00:46 UTC, anithaamarnath commented on package.json
> +    "@chakra-ui/react": "^2.8.1",
If we not implement chakra-ui, we can uninstall

2023-10-27 00:46 UTC, anithaamarnath commented on src/pages/ViewAccount/Profile.jsx
> +          support@yummydash.com
Remove this information because we not gonna support for now
Thanks

2023-10-27 04:42 UTC, kavithashanmugan approved these changes

2023-10-27 06:10 UTC, merged